### ISSUE TITLE
Docker support fails even with privileged flag

### ISSUE THREAD

**Issue by braunsonm** [JetBrains/teamcity-docker-agent#16]
The following teamcity agent:

```
    teamcity-agent-stuff:
        image: jetbrains/teamcity-agent:latest
        restart: always
        environment:
            - "SERVER_URL=http://something:8111"
            - "DOCKER_IN_DOCKER=start"
            - "AGENT_NAME=stuff"
        volumes:
            - teamcity-agent-stuff:/data/teamcity_agent/conf
        networks:
          - teamcity-network
        # Adds docker in docker support
        privileged: true
```

Still fails when trying a Docker Build step.
`Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

**Comment by braunsonm** [comment]
The agent itself states it has Docker Build support, however the agent cannot find the docker daemon socket to run any docker build commands.

**Comment by braunsonm** [comment]
I found that this can be fixed by entering the container and running `service docker start`
It turns out the containers don't automatically start the daemon on their own for some reason.

Note the following:
```
root@e607d9db05de:/services# cat run-docker.sh
#!/bin/bash

if [ "$DOCKER_IN_DOCKER" = "start" ] ; then
 service docker start
 echo "Docker daemon started"
firoot@e607d9db05de:/services# echo $DOCKER_IN_DOCKER
start
```

As you can see, my DOCKER_IN_DOCKER variable is set, however the script did not run on startup.

**Comment by JamesMcMahon** [comment]
Hey,

The `DOCKER_IN_DOCKER` setting works for me. They could have updated the image or it could be the way I am formatting it.

This is what I have:

```yaml
teamcity-agent:
  image: jetbrains/teamcity-agent:latest
  environment:
    - SERVER_URL=http://server:8111
    - AGENT_NAME=regular_agent
    - DOCKER_IN_DOCKER=start
  privileged: true
```

So I no longer see the `failed to get default registry endpoint from daemon` error, but I do now see this error:

> docker: Error response from daemon: error creating aufs mount to /var/lib/docker/aufs/mnt/3d9374e474dc71e700bc70591563f5d79409088b4a9ea75b7a338fbc1b2c24f8-init: invalid argument.
See 'docker run --help'.

Anyone from the Jetbrains team have any idea what might be going on?

**Comment by VladRassokhin** [comment]
@JamesMcMahon  I haven't tested it myself but [seems](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/#docker-in-docker-the-ugly) it's impossible to use aufs-in-aufs.
AFAIR we don't pass outer docker socket into agent, but running another docker service inside agent, so that approach declares some limitations yet provides security.

**Comment by JamesMcMahon** [comment]
Thanks for the answer @VladRassokhin, does that mean that the `DOCKER_IN_DOCKER` option is broken? If so it may be good to remove the option all together to avoid people putting in cycles to get it to work.

I actually did get a little further down the road then my post above. I was being a dummy and didn't have a volume mount, which is what was causing that error. Once I added the volume mount I got a completely different error, which I sadly don't have one me.

**Comment by braunsonm** [comment]
@JamesMcMahon
The option doesn't work in aufs possibly. It works with other file systems.

**Comment by JamesMcMahon** [comment]
Ah ok, I've never dived into Docker storage drivers. What is the correct option to use to make this work? Or is it basically, works on everything else except aufs?

**Comment by braunsonm** [comment]
I use overlay2 and it works fine other than the issue I mentioned above about failing to auto start. You can enter the container and start it yourself and then it's fine.

**Comment by drawm** [comment]
Same problem here.
The docker service seems to stop after ~20sec, even if I start it manualy.
Using `overlay2` (also tested with `aufs`)
Docker version 18.03.0-ce, build 0520e24302

```bash
# From inside the agent's container
root@f2691c25f7f7:/# service docker status
 * Docker is not running
root@f2691c25f7f7:/# service docker start
 * Starting Docker: docker                                                                                                                                                              [ OK ] 
root@f2691c25f7f7:/# service docker status
 * Docker is running
root@f2691c25f7f7:/# time docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

real	0m23.089s
user	0m0.010s
sys	0m0.011s
root@f2691c25f7f7:/# service docker status
 * Docker is not running
```

```yaml
#docker-compose.yml
version: '3.1'

networks:
  ext:

volumes:
  docker_volumes:

services:

  agent:
    image: jetbrains/teamcity-agent:2017.2.3
    environment:
      - DOCKER_IN_DOCKER=start
      - SERVER_URL=server.address
    volumes:
      - docker_volumes:/var/lib/docker
    privileged: true
    networks:
      - ext
```

Any idea on how to fix this?

**Comment by drawm** [comment]
Same result with the less secure approach...
```yaml
version: '3.1'

networks:
  ext:

services:
  agent:
    image: jetbrains/teamcity-agent
    environment:
      - DOCKER_IN_DOCKER=start
      - SERVER_URL=server.address
    volumes:
      - volumes/temp=/opt/buildagent/temp
      - volumes/work=/opt/buildagent/work
    networks:
      - ext
```

Logs when running `service docker start`
```
time="2018-04-04T20:34:15.007189666Z" level=info msg="libcontainerd: started new docker-containerd process" pid=3002
time="2018-04-04T20:34:15Z" level=info msg="starting containerd" module=containerd revision=89623f28b87a6004d4b785663257362d1658a729 version=v1.0.0 
time="2018-04-04T20:34:15Z" level=info msg="setting subreaper..." module=containerd 
time="2018-04-04T20:34:15Z" level=info msg="changing OOM score to -500" module=containerd 
containerd: write /proc/3002/oom_score_adj: permission denied
time="2018-04-04T20:34:15.022913374Z" level=error msg="containerd did not exit successfully" error="exit status 1" module=libcontainerd
Failed to connect to containerd: failed to dial "/var/run/docker/containerd/docker-containerd.sock": dial unix:///var/run/docker/containerd/docker-containerd.sock: timeout
```

`/var/run/docker/containerd/docker-containerd.sock` does not exist
```bash
root@758c10b37338:/# ls -lah /var/run/docker/containerd/
total 20K
drwx------ 3 root root 4.0K Apr  4 20:36 .
drwx------ 3 root root 4.0K Apr  4 20:18 ..
-rw------- 1 root root  559 Apr  4 20:36 containerd.toml
drwx--x--x 2 root root 4.0K Apr  4 20:18 daemon
-rw-r----- 1 root root    4 Apr  4 20:36 docker-containerd.pid # <--- disapear when docker service stop
```

Is the path to docker-containerd.sock invalid? can we change it with a config?

**Comment by drawm** [comment]
I switched back to the secure method
```bash
docker-compose down --volumes
cp ../docker-compose.secure.ymp ./docker-compose.yml
docker-compose up
```
Stangely, the `containerd.sock` is present and the docker service is running.
```bash
root@9829cc5ff57f:/# ls -lah /var/run/docker/containerd/
total 20K
drwx------ 3 root root 4.0K Apr  4 20:40 .
drwx------ 6 root root 4.0K Apr  4 20:40 ..
-rw------- 1 root root  559 Apr  4 20:40 containerd.toml
drwx--x--x 3 root root 4.0K Apr  4 20:40 daemon
srw-rw---- 1 root root    0 Apr  4 20:40 docker-containerd-debug.sock
-rw-r----- 1 root root    2 Apr  4 20:40 docker-containerd.pid
srw-rw---- 1 root root    0 Apr  4 20:40 docker-containerd.sock
root@9829cc5ff57f:/# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@9829cc5ff57f:/# service docker status
 * Docker is running
```

But when I tried to run a build configuration agains that agent, the build simply froze...
The build log simply print:
`[20:42:54]The build is removed from the queue to be prepared for the start`
Its been +10min since the build failed, the agent has been removed from Teamcity but the build is still waiting for it to reply.
![2018_04_04_16h56_49s](https://user-images.githubusercontent.com/3661129/38334483-76ab6870-3829-11e8-82ee-3eca5e014bae.png)


This is not what I expect from Jetbrain's products... I wonder how I can justify Teamcity's cost to my boss when I have to spend hours to debug it.

**Comment by drawm** [comment]
Possible solution that worked for me.
The documentation on https://hub.docker.com/r/jetbrains/teamcity-agent/ does not tell you why you need all thoses volumes. Turns out they aren't ment to be shared between your agent, each instance should have its own volumes.
I simply removed the volumes as we do not care about the warm up time and everything started working.

Based on this issue https://youtrack.jetbrains.com/issue/TW-53769

Final docker-compose
```yaml
version: '3.1'

networks:
  ext:

services:

  agent:
    image: jetbrains/teamcity-agent:2017.2.3
    environment:
      - DOCKER_IN_DOCKER=start
      - SERVER_URL=server.address
    privileged: true
    networks:
      - ext
```

**Comment by braunsonm** [comment]
@drawm That is clearly shown in the documentation for using this container. It is also common sense for agents to not share their configuration with other agents.

Your replies have no relation to the issue I reported,

**Comment by VladRassokhin** [comment]
@ChaosCA Well, I've tried it myself and cannot reporoduce issue both on local installation (usign dokcer-compose) and GCP (using kubernetes).
Here's my docker-compose.yaml content
```yaml
version : '2'

services:
  server:
    image: 'jetbrains/teamcity-server:2017.2.3'
    ports:
      - 8111:8111
    environment:
      - TEAMCITY_SERVER_MEM_OPTS="-Xmx750m"
    volumes:
      - ./data:/data/teamcity_server/datadir
      - ./logs:/opt/teamcity/logs
  agent:
    image: 'jetbrains/teamcity-agent:2017.2.3'
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=full-agent
      - DOCKER_IN_DOCKER=start
    privileged: true
```

Could you please share docker logs from agent instance (`/var/log/docker.log`)
