### ISSUE TITLE
Permission issue when attempting to run in docker swarm

### ISSUE THREAD

**Issue by bushshrub** [JetBrains/teamcity-docker-agent#72]
Hi, I'm running TeamCity and TeamCity Agent in a Docker Swarm configuration and I'm seeing this error:

```
cp: cannot create regular file '/data/teamcity_agent/conf/buildAgent.dist.properties': Permission denied
cp: cannot create regular file '/data/teamcity_agent/conf/buildAgent.properties': Permission denied
cp: cannot create regular file '/data/teamcity_agent/conf/log4j.dtd': Permission denied
cp: cannot create regular file '/data/teamcity_agent/conf/teamcity-agent-log4j.xml': Permission denied
```

My compose configuration:

```yaml
services:
    teamcity:
        image: jetbrains/teamcity-server:latest
        restart: on-failure
        ports:
            - "6920:8111"
        volumes:
            - "/srv/teamcity/datadir:/data/teamcity_server/datadir"
            - "/srv/teamcity/logs:/opt/teamcity/logs"
    teamcity_agent:
        image: jetbrains/teamcity-agent:2020.1.2-linux-sudo
        restart: on-failure
        volumes:
            - "/srv/teamcity_agent/conf:/data/teamcity_agent/conf"
        environment:
            - SERVER_URL="http://tc:8111"
        links:
            - "teamcity:tc"
```

Results of the command `ls -l /srv/teamcity_agent: `

```
total 4
drwxr-xr-x 2 root root 4096 Aug 10 11:53 conf
```

Any idea what could be causing this? TeamCity Server seems to be running fine so far
