### ISSUE TITLE
Generating Self Singed Certificated for TeamCity Agent  & Connection to Teamcity Server in Docker

### ISSUE THREAD

**Issue by gauravcanon** [JetBrains/teamcity-docker-agent#74]
We are evaluating Teamcity for an Enterprise solution. 

What I am trying to achieve. 

:white_check_mark:  Create and host Teamcity Server 
:white_check_mark:  It is working with SSL able to access outside the home network
:white_check_mark:  Install Agent 1 and check the connection with the Teamcity server
✗  Agent SSL handshake with Teamcity Server

- I don't know how to set up an agent to talk to the Teamcity server using SSL  tried this [link](https://www.jetbrains.com/help/teamcity/using-https-to-access-teamcity-server.html). But this is for standalone installation not for docker image. 
- Hosting Agent and Teamcity server on same WSL Docker environment 
- Tried this [link](https://www.jetbrains.com/help/teamcity/uploading-ssl-certificates.html). But not clear in terms of docker
- #41  This issue I tried to follow but didn't get working 

My Docker Compose 

```yml
  version: '3.3'
  networks:
     teamcity:
            driver: bridge
  services:
        nginx-proxy:
            container_name: nginx-proxy
            image: jwilder/nginx-proxy
            labels:
                com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
            ports:
                    - "80:80"
                    - "443:443"
            volumes:
                    - /var/run/docker.sock:/tmp/docker.sock:ro
                    - /usr/share/nginx/html
                    - ./teamcity/nginx/certs:/etc/nginx/certs:ro
                    - ./teamcity/nginx/vhost:/etc/nginx/vhost.d
            environment:
                    - DEFAULT_HOST=teamcity.mydomain.com
            networks:
                    - teamcity
        nginx-letsencrypt:
            container_name: nginx-letsencrypt
            image: jrcs/letsencrypt-nginx-proxy-companion
            environment:
                    - NGINX_PROXY_CONTAINER=nginx-proxy
            volumes:
                 - ./teamcity/nginx/certs:/etc/nginx/certs:rw
                 - /var/run/docker.sock:/var/run/docker.sock:ro
            volumes_from:
              - "nginx-proxy"
            networks:
                 - teamcity
        teamcity-server:
                container_name: teamcity-server-instance
                user: root
                volumes:
                    - './teamcity/data:/data/teamcity_server/datadir'
                    - './teamcity/logs/:/opt/teamcity/logs'
                ports:
                    - '8111:8111'
                image: jetbrains/teamcity-server
                environment:
                    - VIRTUAL_HOST=teamcity.mydomain.com
                    - LETSENCRYPT_HOST=teamcity.mydomain.com
                    - LETSENCRYPT_EMAIL=support@mydomain.com
                    - SERVER_URL=teamcity.mydomain.com
                depends_on:
                    - postgres
                networks:
                    - teamcity
        postgres:
                image: postgres:10
                volumes:
                    - ./postgress/srv/postgresql/data:/var/lib/postgresql/data
                environment:
                    - POSTGRES_PASSWORD=******
                    - POSTGRES_USER=*****
                    - POSTGRES_DB=teamcity
                expose:
                    - 5432
                ports:
                    - "5432:5432"
                networks:
                    - teamcity
        teamcity-agent-1:
                container_name: teamcity-agent-1
                user: root
                environment:
                    - 'SERVER_URL=https://teamcity-server-instance:8111'
                    - DOCKER_IN_DOCKER=start
                volumes:
                    - ./agent1/conf:/data/teamcity_agent/conf
                    - ./agent1/volumes:/var/lib/docker

                privileged: true
                depends_on:
                    - teamcity-server-instance
                links:
                  - "teamcity-server-instance"
                image: jetbrains/teamcity-agent
                networks:
                    - teamcity                
 ```

Error from Agent Log : 

```
[2021-12-29 07:09:19,354]   WARN - buildServer.AGENT.registration - Error while asking server for the communication protocols via URL https://teamcity.mydomain.com/app/agents/protocols. Will try later: java.net.ConnectException: Connection refused (Connection refused) (enable debug to see stacktrace)

[2021-12-29 07:09:19,354]   WARN - buildServer.AGENT.registration - Error registering on the server via URL https://teamcity.mydomain.com. Will continue repeating connection attempts.
```

What I am missing
