### ISSUE TITLE
cgroups: cgroup mountpoint does not exist: unknown

### ISSUE THREAD

**Issue by bushshrub** [JetBrains/teamcity-docker-agent#75]
All builds fail with this error
```yaml
teamcity-agent-1:
    image: jetbrains/teamcity-agent:2021.2.2-linux-sudo
    container_name: teamcity-agent-1
    privileged: true
    volumes:
      - ./teamcity/agent-1:/data/teamcity_agent/conf
      - tc_docker_volumes:/var/lib/docker
    environment: 
      DOCKER_IN_DOCKER: start
      SERVER_URL: http://teamcity:8111
      AGENT_NAME: local-docker-agent
    networks:
      teamcity-net:
```

`docker exec -it teamcity-agent-1 bash`:
```
buildagent@c67f3830f828:/$ docker run hello-world
docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.
ERRO[0000] error waiting for container: context canceled 
buildagent@c67f3830f828:/$ 
```

Steps I've tried:
https://teamcity-support.jetbrains.com/hc/en-us/community/posts/4405053438354-cgroup-mountpoint-does-not-exist
Output:
```
/usr/sbin/grub-probe: error: failed to get canonical path of `overlay'.
```

https://github.com/docker/for-linux/issues/219#issuecomment-375160449
```
$ sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
mount: /sys/fs/cgroup/systemd: permission denied.
```
